title: Philip Pages
description: A Jekyll theme for documentation
baseurl: ""
url: "https://philip-spb.github.io"
github_username: philip-spb

theme: just-the-docs
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-feed
  - jekyll-seo-tag

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

footer_content: |
  <a href="#top" id="back-to-top">На верх ↑</a>
  <script src="/assets/js/script.js"></script>
