title: Just the Docs
description: A Jekyll theme for documentation
baseurl: ""
url: "https://philip-spb.github.io"
github_username:  philip-spb

theme: just-the-docs
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-feed
